// Tesla tedapi API Protocol Buffer definition (tedapi.proto)
//
// Create tedapi_pb2.py for use in projects using the protoc compiler:
//     protoc --python_out=. tedapi.proto
//
// Author: Jason A. Cox - Date: 22 Nov 2023 - Version: 1.1
//
// For more information see https://github.com/jasonacox/pypowerwall

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: tedapi.proto

package tedapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageEnvelope       `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tail          *Tail                  `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tedapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessage() *MessageEnvelope {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetTail() *Tail {
	if x != nil {
		return x.Tail
	}
	return nil
}

type MessageEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeliveryChannel int32                  `protobuf:"varint,1,opt,name=deliveryChannel,proto3" json:"deliveryChannel,omitempty"`
	Sender          *Participant           `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient       *Participant           `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Firmware        *FirmwareType          `protobuf:"bytes,4,opt,name=firmware,proto3" json:"firmware,omitempty"`
	Config          *ConfigType            `protobuf:"bytes,15,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Payload         *QueryType             `protobuf:"bytes,16,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	mi := &file_tedapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{1}
}

func (x *MessageEnvelope) GetDeliveryChannel() int32 {
	if x != nil {
		return x.DeliveryChannel
	}
	return 0
}

func (x *MessageEnvelope) GetSender() *Participant {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageEnvelope) GetRecipient() *Participant {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *MessageEnvelope) GetFirmware() *FirmwareType {
	if x != nil {
		return x.Firmware
	}
	return nil
}

func (x *MessageEnvelope) GetConfig() *ConfigType {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MessageEnvelope) GetPayload() *QueryType {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Participant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*Participant_Din
	//	*Participant_TeslaService
	//	*Participant_Local
	//	*Participant_AuthorizedClient
	Id            isParticipant_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_tedapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{2}
}

func (x *Participant) GetId() isParticipant_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Participant) GetDin() string {
	if x != nil {
		if x, ok := x.Id.(*Participant_Din); ok {
			return x.Din
		}
	}
	return ""
}

func (x *Participant) GetTeslaService() int32 {
	if x != nil {
		if x, ok := x.Id.(*Participant_TeslaService); ok {
			return x.TeslaService
		}
	}
	return 0
}

func (x *Participant) GetLocal() int32 {
	if x != nil {
		if x, ok := x.Id.(*Participant_Local); ok {
			return x.Local
		}
	}
	return 0
}

func (x *Participant) GetAuthorizedClient() int32 {
	if x != nil {
		if x, ok := x.Id.(*Participant_AuthorizedClient); ok {
			return x.AuthorizedClient
		}
	}
	return 0
}

type isParticipant_Id interface {
	isParticipant_Id()
}

type Participant_Din struct {
	Din string `protobuf:"bytes,1,opt,name=din,proto3,oneof"`
}

type Participant_TeslaService struct {
	TeslaService int32 `protobuf:"varint,2,opt,name=teslaService,proto3,oneof"`
}

type Participant_Local struct {
	Local int32 `protobuf:"varint,3,opt,name=local,proto3,oneof"`
}

type Participant_AuthorizedClient struct {
	AuthorizedClient int32 `protobuf:"varint,4,opt,name=authorizedClient,proto3,oneof"`
}

func (*Participant_Din) isParticipant_Id() {}

func (*Participant_TeslaService) isParticipant_Id() {}

func (*Participant_Local) isParticipant_Id() {}

func (*Participant_AuthorizedClient) isParticipant_Id() {}

type Tail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tail) Reset() {
	*x = Tail{}
	mi := &file_tedapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tail) ProtoMessage() {}

func (x *Tail) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tail.ProtoReflect.Descriptor instead.
func (*Tail) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{3}
}

func (x *Tail) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type FirmwareType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*FirmwareType_Request
	//	*FirmwareType_System
	Id            isFirmwareType_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareType) Reset() {
	*x = FirmwareType{}
	mi := &file_tedapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareType) ProtoMessage() {}

func (x *FirmwareType) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareType.ProtoReflect.Descriptor instead.
func (*FirmwareType) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{4}
}

func (x *FirmwareType) GetId() isFirmwareType_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FirmwareType) GetRequest() string {
	if x != nil {
		if x, ok := x.Id.(*FirmwareType_Request); ok {
			return x.Request
		}
	}
	return ""
}

func (x *FirmwareType) GetSystem() *FirmwarePayload {
	if x != nil {
		if x, ok := x.Id.(*FirmwareType_System); ok {
			return x.System
		}
	}
	return nil
}

type isFirmwareType_Id interface {
	isFirmwareType_Id()
}

type FirmwareType_Request struct {
	Request string `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type FirmwareType_System struct {
	System *FirmwarePayload `protobuf:"bytes,3,opt,name=system,proto3,oneof"`
}

func (*FirmwareType_Request) isFirmwareType_Id() {}

func (*FirmwareType_System) isFirmwareType_Id() {}

type FirmwarePayload struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Gateway      *EcuId                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Din          string                 `protobuf:"bytes,2,opt,name=din,proto3" json:"din,omitempty"`
	Version      *FirmwareVersion       `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // Tesla: firmwareVersion; kept as `version`
	SystemUpdate *SystemUpdate          `protobuf:"bytes,5,opt,name=systemUpdate,proto3" json:"systemUpdate,omitempty"`
	DeviceType   int32                  `protobuf:"varint,6,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	// Tesla: complianceInformation (ComplianceInformation{radioLegalInformation}).
	// Kept as `wireless`/DeviceArray -- wire-identical and an established output field.
	Wireless                   *DeviceArray `protobuf:"bytes,7,opt,name=wireless,proto3" json:"wireless,omitempty"`
	InstalledFirmwareSignature []byte       `protobuf:"bytes,8,opt,name=installedFirmwareSignature,proto3" json:"installedFirmwareSignature,omitempty"`
	OfflineFirmwareSignature   []byte       `protobuf:"bytes,9,opt,name=offlineFirmwareSignature,proto3" json:"offlineFirmwareSignature,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *FirmwarePayload) Reset() {
	*x = FirmwarePayload{}
	mi := &file_tedapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwarePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwarePayload) ProtoMessage() {}

func (x *FirmwarePayload) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwarePayload.ProtoReflect.Descriptor instead.
func (*FirmwarePayload) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{5}
}

func (x *FirmwarePayload) GetGateway() *EcuId {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *FirmwarePayload) GetDin() string {
	if x != nil {
		return x.Din
	}
	return ""
}

func (x *FirmwarePayload) GetVersion() *FirmwareVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *FirmwarePayload) GetSystemUpdate() *SystemUpdate {
	if x != nil {
		return x.SystemUpdate
	}
	return nil
}

func (x *FirmwarePayload) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *FirmwarePayload) GetWireless() *DeviceArray {
	if x != nil {
		return x.Wireless
	}
	return nil
}

func (x *FirmwarePayload) GetInstalledFirmwareSignature() []byte {
	if x != nil {
		return x.InstalledFirmwareSignature
	}
	return nil
}

func (x *FirmwarePayload) GetOfflineFirmwareSignature() []byte {
	if x != nil {
		return x.OfflineFirmwareSignature
	}
	return nil
}

type EcuId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    string                 `protobuf:"bytes,1,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcuId) Reset() {
	*x = EcuId{}
	mi := &file_tedapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcuId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcuId) ProtoMessage() {}

func (x *EcuId) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcuId.ProtoReflect.Descriptor instead.
func (*EcuId) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{6}
}

func (x *EcuId) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *EcuId) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type FirmwareVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Githash       []byte                 `protobuf:"bytes,2,opt,name=githash,proto3" json:"githash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareVersion) Reset() {
	*x = FirmwareVersion{}
	mi := &file_tedapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareVersion) ProtoMessage() {}

func (x *FirmwareVersion) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareVersion.ProtoReflect.Descriptor instead.
func (*FirmwareVersion) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{7}
}

func (x *FirmwareVersion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FirmwareVersion) GetGithash() []byte {
	if x != nil {
		return x.Githash
	}
	return nil
}

// System firmware-update state (FirmwarePayload field 5). Field names/types are
// from Tesla's own schema (energy_device.v1 CommonAPIGetSystemInfoResponse).
// The original reverse-engineered proto modeled only field 2 (as FirmwareFive.d)
// -- that is `updateStatus`; the rest of the message was skipped.
type SystemUpdate struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	HandshakeResult         int32                  `protobuf:"varint,1,opt,name=handshakeResult,proto3" json:"handshakeResult,omitempty"`
	UpdateStatus            int32                  `protobuf:"varint,2,opt,name=updateStatus,proto3" json:"updateStatus,omitempty"`
	ServerStagedVersion     *FirmwareVersion       `protobuf:"bytes,3,opt,name=serverStagedVersion,proto3" json:"serverStagedVersion,omitempty"`
	TotalBytes              uint64                 `protobuf:"varint,4,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
	BytesOffset             uint64                 `protobuf:"varint,5,opt,name=bytesOffset,proto3" json:"bytesOffset,omitempty"`
	EstimatedBytesPerSecond uint64                 `protobuf:"varint,6,opt,name=estimatedBytesPerSecond,proto3" json:"estimatedBytesPerSecond,omitempty"`
	LastHandshakeTimestamp  uint64                 `protobuf:"varint,7,opt,name=lastHandshakeTimestamp,proto3" json:"lastHandshakeTimestamp,omitempty"`
	LastUpdateResult        int32                  `protobuf:"varint,8,opt,name=lastUpdateResult,proto3" json:"lastUpdateResult,omitempty"`
	ServerStagedPackages    []*ServerStagedPackage `protobuf:"bytes,9,rep,name=serverStagedPackages,proto3" json:"serverStagedPackages,omitempty"`
	IsSideloading           bool                   `protobuf:"varint,10,opt,name=isSideloading,proto3" json:"isSideloading,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SystemUpdate) Reset() {
	*x = SystemUpdate{}
	mi := &file_tedapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUpdate) ProtoMessage() {}

func (x *SystemUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUpdate.ProtoReflect.Descriptor instead.
func (*SystemUpdate) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{8}
}

func (x *SystemUpdate) GetHandshakeResult() int32 {
	if x != nil {
		return x.HandshakeResult
	}
	return 0
}

func (x *SystemUpdate) GetUpdateStatus() int32 {
	if x != nil {
		return x.UpdateStatus
	}
	return 0
}

func (x *SystemUpdate) GetServerStagedVersion() *FirmwareVersion {
	if x != nil {
		return x.ServerStagedVersion
	}
	return nil
}

func (x *SystemUpdate) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *SystemUpdate) GetBytesOffset() uint64 {
	if x != nil {
		return x.BytesOffset
	}
	return 0
}

func (x *SystemUpdate) GetEstimatedBytesPerSecond() uint64 {
	if x != nil {
		return x.EstimatedBytesPerSecond
	}
	return 0
}

func (x *SystemUpdate) GetLastHandshakeTimestamp() uint64 {
	if x != nil {
		return x.LastHandshakeTimestamp
	}
	return 0
}

func (x *SystemUpdate) GetLastUpdateResult() int32 {
	if x != nil {
		return x.LastUpdateResult
	}
	return 0
}

func (x *SystemUpdate) GetServerStagedPackages() []*ServerStagedPackage {
	if x != nil {
		return x.ServerStagedPackages
	}
	return nil
}

func (x *SystemUpdate) GetIsSideloading() bool {
	if x != nil {
		return x.IsSideloading
	}
	return false
}

type ServerStagedPackage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl         string                 `protobuf:"bytes,1,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	PackageId           uint64                 `protobuf:"varint,2,opt,name=packageId,proto3" json:"packageId,omitempty"`
	PackageSignature    []byte                 `protobuf:"bytes,3,opt,name=packageSignature,proto3" json:"packageSignature,omitempty"`
	ServerStagedVersion *FirmwareVersion       `protobuf:"bytes,4,opt,name=serverStagedVersion,proto3" json:"serverStagedVersion,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerStagedPackage) Reset() {
	*x = ServerStagedPackage{}
	mi := &file_tedapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStagedPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStagedPackage) ProtoMessage() {}

func (x *ServerStagedPackage) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStagedPackage.ProtoReflect.Descriptor instead.
func (*ServerStagedPackage) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{9}
}

func (x *ServerStagedPackage) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ServerStagedPackage) GetPackageId() uint64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *ServerStagedPackage) GetPackageSignature() []byte {
	if x != nil {
		return x.PackageSignature
	}
	return nil
}

func (x *ServerStagedPackage) GetServerStagedVersion() *FirmwareVersion {
	if x != nil {
		return x.ServerStagedVersion
	}
	return nil
}

type DeviceArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        []*DeviceInfo          `protobuf:"bytes,1,rep,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceArray) Reset() {
	*x = DeviceArray{}
	mi := &file_tedapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceArray) ProtoMessage() {}

func (x *DeviceArray) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceArray.ProtoReflect.Descriptor instead.
func (*DeviceArray) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceArray) GetDevice() []*DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *StringValue           `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Model         *StringValue           `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	FccId         *StringValue           `protobuf:"bytes,3,opt,name=fcc_id,json=fccId,proto3" json:"fcc_id,omitempty"`
	Ic            *StringValue           `protobuf:"bytes,4,opt,name=ic,proto3" json:"ic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_tedapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceInfo) GetCompany() *StringValue {
	if x != nil {
		return x.Company
	}
	return nil
}

func (x *DeviceInfo) GetModel() *StringValue {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *DeviceInfo) GetFccId() *StringValue {
	if x != nil {
		return x.FccId
	}
	return nil
}

func (x *DeviceInfo) GetIc() *StringValue {
	if x != nil {
		return x.Ic
	}
	return nil
}

type QueryType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Send          *PayloadQuerySend      `protobuf:"bytes,1,opt,name=send,proto3,oneof" json:"send,omitempty"`
	Recv          *PayloadString         `protobuf:"bytes,2,opt,name=recv,proto3,oneof" json:"recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryType) Reset() {
	*x = QueryType{}
	mi := &file_tedapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryType) ProtoMessage() {}

func (x *QueryType) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryType.ProtoReflect.Descriptor instead.
func (*QueryType) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{12}
}

func (x *QueryType) GetSend() *PayloadQuerySend {
	if x != nil {
		return x.Send
	}
	return nil
}

func (x *QueryType) GetRecv() *PayloadString {
	if x != nil {
		return x.Recv
	}
	return nil
}

type PayloadQuerySend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           *int32                 `protobuf:"varint,1,opt,name=num,proto3,oneof" json:"num,omitempty"`
	Payload       *PayloadString         `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	Code          []byte                 `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code,omitempty"`
	B             *StringValue           `protobuf:"bytes,4,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadQuerySend) Reset() {
	*x = PayloadQuerySend{}
	mi := &file_tedapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadQuerySend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadQuerySend) ProtoMessage() {}

func (x *PayloadQuerySend) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadQuerySend.ProtoReflect.Descriptor instead.
func (*PayloadQuerySend) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{13}
}

func (x *PayloadQuerySend) GetNum() int32 {
	if x != nil && x.Num != nil {
		return *x.Num
	}
	return 0
}

func (x *PayloadQuerySend) GetPayload() *PayloadString {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PayloadQuerySend) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *PayloadQuerySend) GetB() *StringValue {
	if x != nil {
		return x.B
	}
	return nil
}

type ConfigType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*ConfigType_Send
	//	*ConfigType_Recv
	Config        isConfigType_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigType) Reset() {
	*x = ConfigType{}
	mi := &file_tedapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigType) ProtoMessage() {}

func (x *ConfigType) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigType.ProtoReflect.Descriptor instead.
func (*ConfigType) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigType) GetConfig() isConfigType_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigType) GetSend() *PayloadConfigSend {
	if x != nil {
		if x, ok := x.Config.(*ConfigType_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *ConfigType) GetRecv() *PayloadConfigRecv {
	if x != nil {
		if x, ok := x.Config.(*ConfigType_Recv); ok {
			return x.Recv
		}
	}
	return nil
}

type isConfigType_Config interface {
	isConfigType_Config()
}

type ConfigType_Send struct {
	Send *PayloadConfigSend `protobuf:"bytes,1,opt,name=send,proto3,oneof"`
}

type ConfigType_Recv struct {
	Recv *PayloadConfigRecv `protobuf:"bytes,2,opt,name=recv,proto3,oneof"`
}

func (*ConfigType_Send) isConfigType_Config() {}

func (*ConfigType_Recv) isConfigType_Config() {}

type PayloadConfigSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadConfigSend) Reset() {
	*x = PayloadConfigSend{}
	mi := &file_tedapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadConfigSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadConfigSend) ProtoMessage() {}

func (x *PayloadConfigSend) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadConfigSend.ProtoReflect.Descriptor instead.
func (*PayloadConfigSend) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{15}
}

func (x *PayloadConfigSend) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *PayloadConfigSend) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type PayloadConfigRecv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *ConfigString          `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Code          []byte                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadConfigRecv) Reset() {
	*x = PayloadConfigRecv{}
	mi := &file_tedapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadConfigRecv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadConfigRecv) ProtoMessage() {}

func (x *PayloadConfigRecv) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadConfigRecv.ProtoReflect.Descriptor instead.
func (*PayloadConfigRecv) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{16}
}

func (x *PayloadConfigRecv) GetFile() *ConfigString {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PayloadConfigRecv) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type ConfigString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,100,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigString) Reset() {
	*x = ConfigString{}
	mi := &file_tedapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigString) ProtoMessage() {}

func (x *ConfigString) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigString.ProtoReflect.Descriptor instead.
func (*ConfigString) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigString) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigString) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PayloadString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadString) Reset() {
	*x = PayloadString{}
	mi := &file_tedapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadString) ProtoMessage() {}

func (x *PayloadString) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadString.ProtoReflect.Descriptor instead.
func (*PayloadString) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{18}
}

func (x *PayloadString) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PayloadString) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StringValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValue) Reset() {
	*x = StringValue{}
	mi := &file_tedapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValue) ProtoMessage() {}

func (x *StringValue) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValue.ProtoReflect.Descriptor instead.
func (*StringValue) Descriptor() ([]byte, []int) {
	return file_tedapi_proto_rawDescGZIP(), []int{19}
}

func (x *StringValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_tedapi_proto protoreflect.FileDescriptor

const file_tedapi_proto_rawDesc = "" +
	"\n" +
	"\ftedapi.proto\x12\x06tedapi\"^\n" +
	"\aMessage\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.tedapi.MessageEnvelopeR\amessage\x12 \n" +
	"\x04tail\x18\x02 \x01(\v2\f.tedapi.TailR\x04tail\"\xc7\x02\n" +
	"\x0fMessageEnvelope\x12(\n" +
	"\x0fdeliveryChannel\x18\x01 \x01(\x05R\x0fdeliveryChannel\x12+\n" +
	"\x06sender\x18\x02 \x01(\v2\x13.tedapi.ParticipantR\x06sender\x121\n" +
	"\trecipient\x18\x03 \x01(\v2\x13.tedapi.ParticipantR\trecipient\x120\n" +
	"\bfirmware\x18\x04 \x01(\v2\x14.tedapi.FirmwareTypeR\bfirmware\x12/\n" +
	"\x06config\x18\x0f \x01(\v2\x12.tedapi.ConfigTypeH\x00R\x06config\x88\x01\x01\x120\n" +
	"\apayload\x18\x10 \x01(\v2\x11.tedapi.QueryTypeH\x01R\apayload\x88\x01\x01B\t\n" +
	"\a_configB\n" +
	"\n" +
	"\b_payload\"\x93\x01\n" +
	"\vParticipant\x12\x12\n" +
	"\x03din\x18\x01 \x01(\tH\x00R\x03din\x12$\n" +
	"\fteslaService\x18\x02 \x01(\x05H\x00R\fteslaService\x12\x16\n" +
	"\x05local\x18\x03 \x01(\x05H\x00R\x05local\x12,\n" +
	"\x10authorizedClient\x18\x04 \x01(\x05H\x00R\x10authorizedClientB\x04\n" +
	"\x02id\"\x1c\n" +
	"\x04Tail\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"c\n" +
	"\fFirmwareType\x12\x1a\n" +
	"\arequest\x18\x02 \x01(\tH\x00R\arequest\x121\n" +
	"\x06system\x18\x03 \x01(\v2\x17.tedapi.FirmwarePayloadH\x00R\x06systemB\x04\n" +
	"\x02id\"\x86\x03\n" +
	"\x0fFirmwarePayload\x12'\n" +
	"\agateway\x18\x01 \x01(\v2\r.tedapi.EcuIdR\agateway\x12\x10\n" +
	"\x03din\x18\x02 \x01(\tR\x03din\x121\n" +
	"\aversion\x18\x03 \x01(\v2\x17.tedapi.FirmwareVersionR\aversion\x128\n" +
	"\fsystemUpdate\x18\x05 \x01(\v2\x14.tedapi.SystemUpdateR\fsystemUpdate\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x06 \x01(\x05R\n" +
	"deviceType\x12/\n" +
	"\bwireless\x18\a \x01(\v2\x13.tedapi.DeviceArrayR\bwireless\x12>\n" +
	"\x1ainstalledFirmwareSignature\x18\b \x01(\fR\x1ainstalledFirmwareSignature\x12:\n" +
	"\x18offlineFirmwareSignature\x18\t \x01(\fR\x18offlineFirmwareSignature\"K\n" +
	"\x05EcuId\x12\x1e\n" +
	"\n" +
	"partNumber\x18\x01 \x01(\tR\n" +
	"partNumber\x12\"\n" +
	"\fserialNumber\x18\x02 \x01(\tR\fserialNumber\"?\n" +
	"\x0fFirmwareVersion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\agithash\x18\x02 \x01(\fR\agithash\"\xfe\x03\n" +
	"\fSystemUpdate\x12(\n" +
	"\x0fhandshakeResult\x18\x01 \x01(\x05R\x0fhandshakeResult\x12\"\n" +
	"\fupdateStatus\x18\x02 \x01(\x05R\fupdateStatus\x12I\n" +
	"\x13serverStagedVersion\x18\x03 \x01(\v2\x17.tedapi.FirmwareVersionR\x13serverStagedVersion\x12\x1e\n" +
	"\n" +
	"totalBytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12 \n" +
	"\vbytesOffset\x18\x05 \x01(\x04R\vbytesOffset\x128\n" +
	"\x17estimatedBytesPerSecond\x18\x06 \x01(\x04R\x17estimatedBytesPerSecond\x126\n" +
	"\x16lastHandshakeTimestamp\x18\a \x01(\x04R\x16lastHandshakeTimestamp\x12*\n" +
	"\x10lastUpdateResult\x18\b \x01(\x05R\x10lastUpdateResult\x12O\n" +
	"\x14serverStagedPackages\x18\t \x03(\v2\x1b.tedapi.ServerStagedPackageR\x14serverStagedPackages\x12$\n" +
	"\risSideloading\x18\n" +
	" \x01(\bR\risSideloading\"\xcc\x01\n" +
	"\x13ServerStagedPackage\x12 \n" +
	"\vdownloadUrl\x18\x01 \x01(\tR\vdownloadUrl\x12\x1c\n" +
	"\tpackageId\x18\x02 \x01(\x04R\tpackageId\x12*\n" +
	"\x10packageSignature\x18\x03 \x01(\fR\x10packageSignature\x12I\n" +
	"\x13serverStagedVersion\x18\x04 \x01(\v2\x17.tedapi.FirmwareVersionR\x13serverStagedVersion\"9\n" +
	"\vDeviceArray\x12*\n" +
	"\x06device\x18\x01 \x03(\v2\x12.tedapi.DeviceInfoR\x06device\"\xb7\x01\n" +
	"\n" +
	"DeviceInfo\x12-\n" +
	"\acompany\x18\x01 \x01(\v2\x13.tedapi.StringValueR\acompany\x12)\n" +
	"\x05model\x18\x02 \x01(\v2\x13.tedapi.StringValueR\x05model\x12*\n" +
	"\x06fcc_id\x18\x03 \x01(\v2\x13.tedapi.StringValueR\x05fccId\x12#\n" +
	"\x02ic\x18\x04 \x01(\v2\x13.tedapi.StringValueR\x02ic\"\x80\x01\n" +
	"\tQueryType\x121\n" +
	"\x04send\x18\x01 \x01(\v2\x18.tedapi.PayloadQuerySendH\x00R\x04send\x88\x01\x01\x12.\n" +
	"\x04recv\x18\x02 \x01(\v2\x15.tedapi.PayloadStringH\x01R\x04recv\x88\x01\x01B\a\n" +
	"\x05_sendB\a\n" +
	"\x05_recv\"\xc3\x01\n" +
	"\x10PayloadQuerySend\x12\x15\n" +
	"\x03num\x18\x01 \x01(\x05H\x00R\x03num\x88\x01\x01\x124\n" +
	"\apayload\x18\x02 \x01(\v2\x15.tedapi.PayloadStringH\x01R\apayload\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x03 \x01(\fH\x02R\x04code\x88\x01\x01\x12&\n" +
	"\x01b\x18\x04 \x01(\v2\x13.tedapi.StringValueH\x03R\x01b\x88\x01\x01B\x06\n" +
	"\x04_numB\n" +
	"\n" +
	"\b_payloadB\a\n" +
	"\x05_codeB\x04\n" +
	"\x02_b\"x\n" +
	"\n" +
	"ConfigType\x12/\n" +
	"\x04send\x18\x01 \x01(\v2\x19.tedapi.PayloadConfigSendH\x00R\x04send\x12/\n" +
	"\x04recv\x18\x02 \x01(\v2\x19.tedapi.PayloadConfigRecvH\x00R\x04recvB\b\n" +
	"\x06config\"9\n" +
	"\x11PayloadConfigSend\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\"Q\n" +
	"\x11PayloadConfigRecv\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.tedapi.ConfigStringR\x04file\x12\x12\n" +
	"\x04code\x18\x02 \x01(\fR\x04code\"6\n" +
	"\fConfigString\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18d \x01(\tR\x04text\"9\n" +
	"\rPayloadString\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"#\n" +
	"\vStringValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueBEZCgithub.com/blackbirdworks/gopowerwall/powerwall/proto/tedapi;tedapib\x06proto3"

var (
	file_tedapi_proto_rawDescOnce sync.Once
	file_tedapi_proto_rawDescData []byte
)

func file_tedapi_proto_rawDescGZIP() []byte {
	file_tedapi_proto_rawDescOnce.Do(func() {
		file_tedapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tedapi_proto_rawDesc), len(file_tedapi_proto_rawDesc)))
	})
	return file_tedapi_proto_rawDescData
}

var file_tedapi_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_tedapi_proto_goTypes = []any{
	(*Message)(nil),             // 0: tedapi.Message
	(*MessageEnvelope)(nil),     // 1: tedapi.MessageEnvelope
	(*Participant)(nil),         // 2: tedapi.Participant
	(*Tail)(nil),                // 3: tedapi.Tail
	(*FirmwareType)(nil),        // 4: tedapi.FirmwareType
	(*FirmwarePayload)(nil),     // 5: tedapi.FirmwarePayload
	(*EcuId)(nil),               // 6: tedapi.EcuId
	(*FirmwareVersion)(nil),     // 7: tedapi.FirmwareVersion
	(*SystemUpdate)(nil),        // 8: tedapi.SystemUpdate
	(*ServerStagedPackage)(nil), // 9: tedapi.ServerStagedPackage
	(*DeviceArray)(nil),         // 10: tedapi.DeviceArray
	(*DeviceInfo)(nil),          // 11: tedapi.DeviceInfo
	(*QueryType)(nil),           // 12: tedapi.QueryType
	(*PayloadQuerySend)(nil),    // 13: tedapi.PayloadQuerySend
	(*ConfigType)(nil),          // 14: tedapi.ConfigType
	(*PayloadConfigSend)(nil),   // 15: tedapi.PayloadConfigSend
	(*PayloadConfigRecv)(nil),   // 16: tedapi.PayloadConfigRecv
	(*ConfigString)(nil),        // 17: tedapi.ConfigString
	(*PayloadString)(nil),       // 18: tedapi.PayloadString
	(*StringValue)(nil),         // 19: tedapi.StringValue
}
var file_tedapi_proto_depIdxs = []int32{
	1,  // 0: tedapi.Message.message:type_name -> tedapi.MessageEnvelope
	3,  // 1: tedapi.Message.tail:type_name -> tedapi.Tail
	2,  // 2: tedapi.MessageEnvelope.sender:type_name -> tedapi.Participant
	2,  // 3: tedapi.MessageEnvelope.recipient:type_name -> tedapi.Participant
	4,  // 4: tedapi.MessageEnvelope.firmware:type_name -> tedapi.FirmwareType
	14, // 5: tedapi.MessageEnvelope.config:type_name -> tedapi.ConfigType
	12, // 6: tedapi.MessageEnvelope.payload:type_name -> tedapi.QueryType
	5,  // 7: tedapi.FirmwareType.system:type_name -> tedapi.FirmwarePayload
	6,  // 8: tedapi.FirmwarePayload.gateway:type_name -> tedapi.EcuId
	7,  // 9: tedapi.FirmwarePayload.version:type_name -> tedapi.FirmwareVersion
	8,  // 10: tedapi.FirmwarePayload.systemUpdate:type_name -> tedapi.SystemUpdate
	10, // 11: tedapi.FirmwarePayload.wireless:type_name -> tedapi.DeviceArray
	7,  // 12: tedapi.SystemUpdate.serverStagedVersion:type_name -> tedapi.FirmwareVersion
	9,  // 13: tedapi.SystemUpdate.serverStagedPackages:type_name -> tedapi.ServerStagedPackage
	7,  // 14: tedapi.ServerStagedPackage.serverStagedVersion:type_name -> tedapi.FirmwareVersion
	11, // 15: tedapi.DeviceArray.device:type_name -> tedapi.DeviceInfo
	19, // 16: tedapi.DeviceInfo.company:type_name -> tedapi.StringValue
	19, // 17: tedapi.DeviceInfo.model:type_name -> tedapi.StringValue
	19, // 18: tedapi.DeviceInfo.fcc_id:type_name -> tedapi.StringValue
	19, // 19: tedapi.DeviceInfo.ic:type_name -> tedapi.StringValue
	13, // 20: tedapi.QueryType.send:type_name -> tedapi.PayloadQuerySend
	18, // 21: tedapi.QueryType.recv:type_name -> tedapi.PayloadString
	18, // 22: tedapi.PayloadQuerySend.payload:type_name -> tedapi.PayloadString
	19, // 23: tedapi.PayloadQuerySend.b:type_name -> tedapi.StringValue
	15, // 24: tedapi.ConfigType.send:type_name -> tedapi.PayloadConfigSend
	16, // 25: tedapi.ConfigType.recv:type_name -> tedapi.PayloadConfigRecv
	17, // 26: tedapi.PayloadConfigRecv.file:type_name -> tedapi.ConfigString
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_tedapi_proto_init() }
func file_tedapi_proto_init() {
	if File_tedapi_proto != nil {
		return
	}
	file_tedapi_proto_msgTypes[1].OneofWrappers = []any{}
	file_tedapi_proto_msgTypes[2].OneofWrappers = []any{
		(*Participant_Din)(nil),
		(*Participant_TeslaService)(nil),
		(*Participant_Local)(nil),
		(*Participant_AuthorizedClient)(nil),
	}
	file_tedapi_proto_msgTypes[4].OneofWrappers = []any{
		(*FirmwareType_Request)(nil),
		(*FirmwareType_System)(nil),
	}
	file_tedapi_proto_msgTypes[12].OneofWrappers = []any{}
	file_tedapi_proto_msgTypes[13].OneofWrappers = []any{}
	file_tedapi_proto_msgTypes[14].OneofWrappers = []any{
		(*ConfigType_Send)(nil),
		(*ConfigType_Recv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tedapi_proto_rawDesc), len(file_tedapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tedapi_proto_goTypes,
		DependencyIndexes: file_tedapi_proto_depIdxs,
		MessageInfos:      file_tedapi_proto_msgTypes,
	}.Build()
	File_tedapi_proto = out.File
	file_tedapi_proto_goTypes = nil
	file_tedapi_proto_depIdxs = nil
}
