// Tesla TEDAPI v2 - package tesla.proto.common.v1
// Extracted from the Tesla mobile app bundle (assets/index.android.bundle).
// Auto-generated by tools/tedapi_v2_extractor; do not hand-edit.
//
// FIDELITY: field numbers and wire types are verbatim from the APK. On the
// wire Tesla encodes every enum field as int32 (proto3 varint) and the app's
// compiled protobuf carries no field->enum binding - so the wire-faithful
// truth for those fields is int32.
//
// CONVENIENCE ABSTRACTION: a field tagged "OSS convenience abstraction" is
// typed here as a named enum purely to make this schema easier for the
// open-source community to read and use. It is WIRE-IDENTICAL to int32
// (proto3 enums are open: unknown values round-trip as their raw int), so it
// never changes the bytes we send nor breaks if Tesla adds a value. Source:
// the Matthew1471 Tesla-API project, corroborated against the 26.10.1 APK
// (the enum exists in the bundle; the field is varint).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: tedapi_v2_common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUIDv4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDv4) Reset() {
	*x = UUIDv4{}
	mi := &file_tedapi_v2_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDv4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDv4) ProtoMessage() {}

func (x *UUIDv4) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDv4.ProtoReflect.Descriptor instead.
func (*UUIDv4) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_common_proto_rawDescGZIP(), []int{0}
}

func (x *UUIDv4) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_tedapi_v2_common_proto protoreflect.FileDescriptor

const file_tedapi_v2_common_proto_rawDesc = "" +
	"\n" +
	"\x16tedapi_v2_common.proto\x12\x15tesla.proto.common.v1\"\x1c\n" +
	"\x06UUIDv4\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textBDZBgithub.com/blackbirdworks/gopowerwall/proto/tedapiv2/common;commonb\x06proto3"

var (
	file_tedapi_v2_common_proto_rawDescOnce sync.Once
	file_tedapi_v2_common_proto_rawDescData []byte
)

func file_tedapi_v2_common_proto_rawDescGZIP() []byte {
	file_tedapi_v2_common_proto_rawDescOnce.Do(func() {
		file_tedapi_v2_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tedapi_v2_common_proto_rawDesc), len(file_tedapi_v2_common_proto_rawDesc)))
	})
	return file_tedapi_v2_common_proto_rawDescData
}

var file_tedapi_v2_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tedapi_v2_common_proto_goTypes = []any{
	(*UUIDv4)(nil), // 0: tesla.proto.common.v1.UUIDv4
}
var file_tedapi_v2_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tedapi_v2_common_proto_init() }
func file_tedapi_v2_common_proto_init() {
	if File_tedapi_v2_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tedapi_v2_common_proto_rawDesc), len(file_tedapi_v2_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tedapi_v2_common_proto_goTypes,
		DependencyIndexes: file_tedapi_v2_common_proto_depIdxs,
		MessageInfos:      file_tedapi_v2_common_proto_msgTypes,
	}.Build()
	File_tedapi_v2_common_proto = out.File
	file_tedapi_v2_common_proto_goTypes = nil
	file_tedapi_v2_common_proto_depIdxs = nil
}
