// TEDAPI v2 LAN transport wrapper (reverse-engineered, not from the app bundle).
//
// The gateway's /tedapi/v1 LAN endpoint frames each request as an outer
// Message { MessageEnvelope message = 1; Tail tail = 2; }. The energy_device
// MessageEnvelope (package tesla.proto.energy_device.v1) carries GraphQLMessages
// at field 16; this wrapper supplies the surrounding Message + Tail, mirroring
// the legacy tedapi.proto Message so the two query paths are wire-equivalent.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: tedapi_v2_transport.proto

package transport

import (
	device "github.com/blackbirdworks/gopowerwall/powerwall/proto/tedapiv2/device"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Message       *device.MessageEnvelope `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tail          *Tail                   `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_tedapi_v2_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessage() *device.MessageEnvelope {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetTail() *Tail {
	if x != nil {
		return x.Tail
	}
	return nil
}

type Tail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tail) Reset() {
	*x = Tail{}
	mi := &file_tedapi_v2_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tail) ProtoMessage() {}

func (x *Tail) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tail.ProtoReflect.Descriptor instead.
func (*Tail) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Tail) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_tedapi_v2_transport_proto protoreflect.FileDescriptor

const file_tedapi_v2_transport_proto_rawDesc = "" +
	"\n" +
	"\x19tedapi_v2_transport.proto\x12\x13tedapi_v2_transport\x1a\x1dtedapi_v2_energy_device.proto\"\x81\x01\n" +
	"\aMessage\x12G\n" +
	"\amessage\x18\x01 \x01(\v2-.tesla.proto.energy_device.v1.MessageEnvelopeR\amessage\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.tedapi_v2_transport.TailR\x04tail\"\x1c\n" +
	"\x04Tail\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05valueBTZRgithub.com/blackbirdworks/gopowerwall/powerwall/proto/tedapiv2/transport;transportb\x06proto3"

var (
	file_tedapi_v2_transport_proto_rawDescOnce sync.Once
	file_tedapi_v2_transport_proto_rawDescData []byte
)

func file_tedapi_v2_transport_proto_rawDescGZIP() []byte {
	file_tedapi_v2_transport_proto_rawDescOnce.Do(func() {
		file_tedapi_v2_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tedapi_v2_transport_proto_rawDesc), len(file_tedapi_v2_transport_proto_rawDesc)))
	})
	return file_tedapi_v2_transport_proto_rawDescData
}

var file_tedapi_v2_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tedapi_v2_transport_proto_goTypes = []any{
	(*Message)(nil),                // 0: tedapi_v2_transport.Message
	(*Tail)(nil),                   // 1: tedapi_v2_transport.Tail
	(*device.MessageEnvelope)(nil), // 2: tesla.proto.energy_device.v1.MessageEnvelope
}
var file_tedapi_v2_transport_proto_depIdxs = []int32{
	2, // 0: tedapi_v2_transport.Message.message:type_name -> tesla.proto.energy_device.v1.MessageEnvelope
	1, // 1: tedapi_v2_transport.Message.tail:type_name -> tedapi_v2_transport.Tail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tedapi_v2_transport_proto_init() }
func file_tedapi_v2_transport_proto_init() {
	if File_tedapi_v2_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tedapi_v2_transport_proto_rawDesc), len(file_tedapi_v2_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tedapi_v2_transport_proto_goTypes,
		DependencyIndexes: file_tedapi_v2_transport_proto_depIdxs,
		MessageInfos:      file_tedapi_v2_transport_proto_msgTypes,
	}.Build()
	File_tedapi_v2_transport_proto = out.File
	file_tedapi_v2_transport_proto_goTypes = nil
	file_tedapi_v2_transport_proto_depIdxs = nil
}
