// Tesla TEDAPI v2 - package tesla.proto.energy_registration.v1
// Extracted from the Tesla mobile app bundle (assets/index.android.bundle).
// Auto-generated by tools/tedapi_v2_extractor; do not hand-edit.
//
// FIDELITY: field numbers and wire types are verbatim from the APK. On the
// wire Tesla encodes every enum field as int32 (proto3 varint) and the app's
// compiled protobuf carries no field->enum binding - so the wire-faithful
// truth for those fields is int32.
//
// CONVENIENCE ABSTRACTION: a field tagged "OSS convenience abstraction" is
// typed here as a named enum purely to make this schema easier for the
// open-source community to read and use. It is WIRE-IDENTICAL to int32
// (proto3 enums are open: unknown values round-trip as their raw int), so it
// never changes the bytes we send nor breaks if Tesla adds a value. Source:
// the Matthew1471 Tesla-API project, corroborated against the 26.10.1 APK
// (the enum exists in the bundle; the field is varint).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: tedapi_v2_energy_registration.proto

package registration

import (
	common "github.com/blackbirdworks/gopowerwall/proto/tedapiv2/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectAccessType int32

const (
	ProjectAccessType_PROJECT_ACCESS_TYPE_INVALID       ProjectAccessType = 0
	ProjectAccessType_PROJECT_ACCESS_TYPE_SERVICE       ProjectAccessType = 1
	ProjectAccessType_PROJECT_ACCESS_TYPE_MANUFACTURING ProjectAccessType = 2
	ProjectAccessType_PROJECT_ACCESS_TYPE_ENGINEERING   ProjectAccessType = 3
	ProjectAccessType_PROJECT_ACCESS_TYPE_PRIVATE       ProjectAccessType = 4
	ProjectAccessType_PROJECT_ACCESS_TYPE_PUBLIC        ProjectAccessType = 5
)

// Enum value maps for ProjectAccessType.
var (
	ProjectAccessType_name = map[int32]string{
		0: "PROJECT_ACCESS_TYPE_INVALID",
		1: "PROJECT_ACCESS_TYPE_SERVICE",
		2: "PROJECT_ACCESS_TYPE_MANUFACTURING",
		3: "PROJECT_ACCESS_TYPE_ENGINEERING",
		4: "PROJECT_ACCESS_TYPE_PRIVATE",
		5: "PROJECT_ACCESS_TYPE_PUBLIC",
	}
	ProjectAccessType_value = map[string]int32{
		"PROJECT_ACCESS_TYPE_INVALID":       0,
		"PROJECT_ACCESS_TYPE_SERVICE":       1,
		"PROJECT_ACCESS_TYPE_MANUFACTURING": 2,
		"PROJECT_ACCESS_TYPE_ENGINEERING":   3,
		"PROJECT_ACCESS_TYPE_PRIVATE":       4,
		"PROJECT_ACCESS_TYPE_PUBLIC":        5,
	}
)

func (x ProjectAccessType) Enum() *ProjectAccessType {
	p := new(ProjectAccessType)
	*p = x
	return p
}

func (x ProjectAccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectAccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[0].Descriptor()
}

func (ProjectAccessType) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[0]
}

func (x ProjectAccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectAccessType.Descriptor instead.
func (ProjectAccessType) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{0}
}

type PropertyType int32

const (
	PropertyType_PROPERTY_TYPE_INVALID                           PropertyType = 0
	PropertyType_PROPERTY_TYPE_SHOPPING_MALL_CENTER              PropertyType = 1
	PropertyType_PROPERTY_TYPE_RESTAURANT                        PropertyType = 2
	PropertyType_PROPERTY_TYPE_GAS_STATION                       PropertyType = 3
	PropertyType_PROPERTY_TYPE_SERVICE_PLAZA_REST_AREA           PropertyType = 4
	PropertyType_PROPERTY_TYPE_HOTEL_RESORT_TOURIST_COMPLEX      PropertyType = 5
	PropertyType_PROPERTY_TYPE_GROCERY_STORE                     PropertyType = 6
	PropertyType_PROPERTY_TYPE_TESLA_STORE_SERVICE_CENTER        PropertyType = 7
	PropertyType_PROPERTY_TYPE_OFFICE                            PropertyType = 8
	PropertyType_PROPERTY_TYPE_RESIDENTIAL_BUILDING              PropertyType = 9
	PropertyType_PROPERTY_TYPE_PARKING_GARAGE_PUBLIC_PARKING_LOT PropertyType = 10
	PropertyType_PROPERTY_TYPE_BANK                              PropertyType = 11
	PropertyType_PROPERTY_TYPE_AIRPORT                           PropertyType = 12
	PropertyType_PROPERTY_TYPE_CITY_VISITOR_CENTER_CITY_PROPERTY PropertyType = 13
	PropertyType_PROPERTY_TYPE_MUSEUM_AMUSEMENT_ATTRACTION       PropertyType = 14
	PropertyType_PROPERTY_TYPE_UNIVERSITY_SCHOOL                 PropertyType = 15
	PropertyType_PROPERTY_TYPE_WINERY                            PropertyType = 16
	PropertyType_PROPERTY_TYPE_AUTOMOTIVE                        PropertyType = 17
	PropertyType_PROPERTY_TYPE_MIXED_USE                         PropertyType = 18
	PropertyType_PROPERTY_TYPE_RECREATION                        PropertyType = 19
	PropertyType_PROPERTY_TYPE_RENTAL_PROPERTY                   PropertyType = 20
	PropertyType_PROPERTY_TYPE_WORKPLACE                         PropertyType = 21
)

// Enum value maps for PropertyType.
var (
	PropertyType_name = map[int32]string{
		0:  "PROPERTY_TYPE_INVALID",
		1:  "PROPERTY_TYPE_SHOPPING_MALL_CENTER",
		2:  "PROPERTY_TYPE_RESTAURANT",
		3:  "PROPERTY_TYPE_GAS_STATION",
		4:  "PROPERTY_TYPE_SERVICE_PLAZA_REST_AREA",
		5:  "PROPERTY_TYPE_HOTEL_RESORT_TOURIST_COMPLEX",
		6:  "PROPERTY_TYPE_GROCERY_STORE",
		7:  "PROPERTY_TYPE_TESLA_STORE_SERVICE_CENTER",
		8:  "PROPERTY_TYPE_OFFICE",
		9:  "PROPERTY_TYPE_RESIDENTIAL_BUILDING",
		10: "PROPERTY_TYPE_PARKING_GARAGE_PUBLIC_PARKING_LOT",
		11: "PROPERTY_TYPE_BANK",
		12: "PROPERTY_TYPE_AIRPORT",
		13: "PROPERTY_TYPE_CITY_VISITOR_CENTER_CITY_PROPERTY",
		14: "PROPERTY_TYPE_MUSEUM_AMUSEMENT_ATTRACTION",
		15: "PROPERTY_TYPE_UNIVERSITY_SCHOOL",
		16: "PROPERTY_TYPE_WINERY",
		17: "PROPERTY_TYPE_AUTOMOTIVE",
		18: "PROPERTY_TYPE_MIXED_USE",
		19: "PROPERTY_TYPE_RECREATION",
		20: "PROPERTY_TYPE_RENTAL_PROPERTY",
		21: "PROPERTY_TYPE_WORKPLACE",
	}
	PropertyType_value = map[string]int32{
		"PROPERTY_TYPE_INVALID":                           0,
		"PROPERTY_TYPE_SHOPPING_MALL_CENTER":              1,
		"PROPERTY_TYPE_RESTAURANT":                        2,
		"PROPERTY_TYPE_GAS_STATION":                       3,
		"PROPERTY_TYPE_SERVICE_PLAZA_REST_AREA":           4,
		"PROPERTY_TYPE_HOTEL_RESORT_TOURIST_COMPLEX":      5,
		"PROPERTY_TYPE_GROCERY_STORE":                     6,
		"PROPERTY_TYPE_TESLA_STORE_SERVICE_CENTER":        7,
		"PROPERTY_TYPE_OFFICE":                            8,
		"PROPERTY_TYPE_RESIDENTIAL_BUILDING":              9,
		"PROPERTY_TYPE_PARKING_GARAGE_PUBLIC_PARKING_LOT": 10,
		"PROPERTY_TYPE_BANK":                              11,
		"PROPERTY_TYPE_AIRPORT":                           12,
		"PROPERTY_TYPE_CITY_VISITOR_CENTER_CITY_PROPERTY": 13,
		"PROPERTY_TYPE_MUSEUM_AMUSEMENT_ATTRACTION":       14,
		"PROPERTY_TYPE_UNIVERSITY_SCHOOL":                 15,
		"PROPERTY_TYPE_WINERY":                            16,
		"PROPERTY_TYPE_AUTOMOTIVE":                        17,
		"PROPERTY_TYPE_MIXED_USE":                         18,
		"PROPERTY_TYPE_RECREATION":                        19,
		"PROPERTY_TYPE_RENTAL_PROPERTY":                   20,
		"PROPERTY_TYPE_WORKPLACE":                         21,
	}
)

func (x PropertyType) Enum() *PropertyType {
	p := new(PropertyType)
	*p = x
	return p
}

func (x PropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[1].Descriptor()
}

func (PropertyType) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[1]
}

func (x PropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyType.Descriptor instead.
func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{1}
}

type RegistrationDeviceType int32

const (
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_INVALID               RegistrationDeviceType = 0
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_POWERWALL             RegistrationDeviceType = 1
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_POWERWALL_EXPANSION   RegistrationDeviceType = 2
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_PV_INVERTER           RegistrationDeviceType = 3
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_WALL_CONNECTOR        RegistrationDeviceType = 4
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_POWERWALL_3           RegistrationDeviceType = 5
	RegistrationDeviceType_REGISTRATION_DEVICE_TYPE_POWERWALL_3_EXPANSION RegistrationDeviceType = 6
)

// Enum value maps for RegistrationDeviceType.
var (
	RegistrationDeviceType_name = map[int32]string{
		0: "REGISTRATION_DEVICE_TYPE_INVALID",
		1: "REGISTRATION_DEVICE_TYPE_POWERWALL",
		2: "REGISTRATION_DEVICE_TYPE_POWERWALL_EXPANSION",
		3: "REGISTRATION_DEVICE_TYPE_PV_INVERTER",
		4: "REGISTRATION_DEVICE_TYPE_WALL_CONNECTOR",
		5: "REGISTRATION_DEVICE_TYPE_POWERWALL_3",
		6: "REGISTRATION_DEVICE_TYPE_POWERWALL_3_EXPANSION",
	}
	RegistrationDeviceType_value = map[string]int32{
		"REGISTRATION_DEVICE_TYPE_INVALID":               0,
		"REGISTRATION_DEVICE_TYPE_POWERWALL":             1,
		"REGISTRATION_DEVICE_TYPE_POWERWALL_EXPANSION":   2,
		"REGISTRATION_DEVICE_TYPE_PV_INVERTER":           3,
		"REGISTRATION_DEVICE_TYPE_WALL_CONNECTOR":        4,
		"REGISTRATION_DEVICE_TYPE_POWERWALL_3":           5,
		"REGISTRATION_DEVICE_TYPE_POWERWALL_3_EXPANSION": 6,
	}
)

func (x RegistrationDeviceType) Enum() *RegistrationDeviceType {
	p := new(RegistrationDeviceType)
	*p = x
	return p
}

func (x RegistrationDeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationDeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[2].Descriptor()
}

func (RegistrationDeviceType) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[2]
}

func (x RegistrationDeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationDeviceType.Descriptor instead.
func (RegistrationDeviceType) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{2}
}

type RegistrationFailure int32

const (
	RegistrationFailure_REGISTRATION_FAILURE_INVALID RegistrationFailure = 0
	RegistrationFailure_REGISTRATION_FAILURE_DEVICES RegistrationFailure = 1
	RegistrationFailure_REGISTRATION_FAILURE_NETWORK RegistrationFailure = 2
)

// Enum value maps for RegistrationFailure.
var (
	RegistrationFailure_name = map[int32]string{
		0: "REGISTRATION_FAILURE_INVALID",
		1: "REGISTRATION_FAILURE_DEVICES",
		2: "REGISTRATION_FAILURE_NETWORK",
	}
	RegistrationFailure_value = map[string]int32{
		"REGISTRATION_FAILURE_INVALID": 0,
		"REGISTRATION_FAILURE_DEVICES": 1,
		"REGISTRATION_FAILURE_NETWORK": 2,
	}
)

func (x RegistrationFailure) Enum() *RegistrationFailure {
	p := new(RegistrationFailure)
	*p = x
	return p
}

func (x RegistrationFailure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationFailure) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[3].Descriptor()
}

func (RegistrationFailure) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[3]
}

func (x RegistrationFailure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationFailure.Descriptor instead.
func (RegistrationFailure) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{3}
}

type RegistrationSource int32

const (
	RegistrationSource_REGISTRATION_SOURCE_INVALID    RegistrationSource = 0
	RegistrationSource_REGISTRATION_SOURCE_AUTOCONFIG RegistrationSource = 1
	RegistrationSource_REGISTRATION_SOURCE_INSTALLER  RegistrationSource = 2
	RegistrationSource_REGISTRATION_SOURCE_CUSTOMER   RegistrationSource = 3
)

// Enum value maps for RegistrationSource.
var (
	RegistrationSource_name = map[int32]string{
		0: "REGISTRATION_SOURCE_INVALID",
		1: "REGISTRATION_SOURCE_AUTOCONFIG",
		2: "REGISTRATION_SOURCE_INSTALLER",
		3: "REGISTRATION_SOURCE_CUSTOMER",
	}
	RegistrationSource_value = map[string]int32{
		"REGISTRATION_SOURCE_INVALID":    0,
		"REGISTRATION_SOURCE_AUTOCONFIG": 1,
		"REGISTRATION_SOURCE_INSTALLER":  2,
		"REGISTRATION_SOURCE_CUSTOMER":   3,
	}
)

func (x RegistrationSource) Enum() *RegistrationSource {
	p := new(RegistrationSource)
	*p = x
	return p
}

func (x RegistrationSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationSource) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[4].Descriptor()
}

func (RegistrationSource) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[4]
}

func (x RegistrationSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationSource.Descriptor instead.
func (RegistrationSource) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{4}
}

type RegistrationStatus int32

const (
	RegistrationStatus_REGISTRATION_STATUS_INVALID                      RegistrationStatus = 0
	RegistrationStatus_REGISTRATION_STATUS_MISSING_INFO                 RegistrationStatus = 1
	RegistrationStatus_REGISTRATION_STATUS_UNDERWAY                     RegistrationStatus = 2
	RegistrationStatus_REGISTRATION_STATUS_ALREADY_REGISTERED           RegistrationStatus = 3
	RegistrationStatus_REGISTRATION_STATUS_FAILED                       RegistrationStatus = 4
	RegistrationStatus_REGISTRATION_STATUS_RETRY_WITH_NO_FURTHER_ACTION RegistrationStatus = 5
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0: "REGISTRATION_STATUS_INVALID",
		1: "REGISTRATION_STATUS_MISSING_INFO",
		2: "REGISTRATION_STATUS_UNDERWAY",
		3: "REGISTRATION_STATUS_ALREADY_REGISTERED",
		4: "REGISTRATION_STATUS_FAILED",
		5: "REGISTRATION_STATUS_RETRY_WITH_NO_FURTHER_ACTION",
	}
	RegistrationStatus_value = map[string]int32{
		"REGISTRATION_STATUS_INVALID":                      0,
		"REGISTRATION_STATUS_MISSING_INFO":                 1,
		"REGISTRATION_STATUS_UNDERWAY":                     2,
		"REGISTRATION_STATUS_ALREADY_REGISTERED":           3,
		"REGISTRATION_STATUS_FAILED":                       4,
		"REGISTRATION_STATUS_RETRY_WITH_NO_FURTHER_ACTION": 5,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[5].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[5]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{5}
}

type SiteRegistrationStatus int32

const (
	SiteRegistrationStatus_SITE_REGISTRATION_STATUS_INVALID    SiteRegistrationStatus = 0
	SiteRegistrationStatus_SITE_REGISTRATION_STATUS_REGISTERED SiteRegistrationStatus = 1
	SiteRegistrationStatus_SITE_REGISTRATION_STATUS_ABANDONED  SiteRegistrationStatus = 2
)

// Enum value maps for SiteRegistrationStatus.
var (
	SiteRegistrationStatus_name = map[int32]string{
		0: "SITE_REGISTRATION_STATUS_INVALID",
		1: "SITE_REGISTRATION_STATUS_REGISTERED",
		2: "SITE_REGISTRATION_STATUS_ABANDONED",
	}
	SiteRegistrationStatus_value = map[string]int32{
		"SITE_REGISTRATION_STATUS_INVALID":    0,
		"SITE_REGISTRATION_STATUS_REGISTERED": 1,
		"SITE_REGISTRATION_STATUS_ABANDONED":  2,
	}
)

func (x SiteRegistrationStatus) Enum() *SiteRegistrationStatus {
	p := new(SiteRegistrationStatus)
	*p = x
	return p
}

func (x SiteRegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SiteRegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[6].Descriptor()
}

func (SiteRegistrationStatus) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[6]
}

func (x SiteRegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SiteRegistrationStatus.Descriptor instead.
func (SiteRegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{6}
}

type WCLoadSharingType int32

const (
	WCLoadSharingType_WC_LOAD_SHARING_TYPE_INVALID  WCLoadSharingType = 0
	WCLoadSharingType_WC_LOAD_SHARING_TYPE_LEADER   WCLoadSharingType = 1
	WCLoadSharingType_WC_LOAD_SHARING_TYPE_FOLLOWER WCLoadSharingType = 2
)

// Enum value maps for WCLoadSharingType.
var (
	WCLoadSharingType_name = map[int32]string{
		0: "WC_LOAD_SHARING_TYPE_INVALID",
		1: "WC_LOAD_SHARING_TYPE_LEADER",
		2: "WC_LOAD_SHARING_TYPE_FOLLOWER",
	}
	WCLoadSharingType_value = map[string]int32{
		"WC_LOAD_SHARING_TYPE_INVALID":  0,
		"WC_LOAD_SHARING_TYPE_LEADER":   1,
		"WC_LOAD_SHARING_TYPE_FOLLOWER": 2,
	}
)

func (x WCLoadSharingType) Enum() *WCLoadSharingType {
	p := new(WCLoadSharingType)
	*p = x
	return p
}

func (x WCLoadSharingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WCLoadSharingType) Descriptor() protoreflect.EnumDescriptor {
	return file_tedapi_v2_energy_registration_proto_enumTypes[7].Descriptor()
}

func (WCLoadSharingType) Type() protoreflect.EnumType {
	return &file_tedapi_v2_energy_registration_proto_enumTypes[7]
}

func (x WCLoadSharingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WCLoadSharingType.Descriptor instead.
func (WCLoadSharingType) EnumDescriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{7}
}

type AnonymizedSiteDetails struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	DeviceDetails []*DeviceDetail         `protobuf:"bytes,1,rep,name=deviceDetails,proto3" json:"deviceDetails,omitempty"`
	City          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Zip           *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizedSiteDetails) Reset() {
	*x = AnonymizedSiteDetails{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizedSiteDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizedSiteDetails) ProtoMessage() {}

func (x *AnonymizedSiteDetails) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizedSiteDetails.ProtoReflect.Descriptor instead.
func (*AnonymizedSiteDetails) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{0}
}

func (x *AnonymizedSiteDetails) GetDeviceDetails() []*DeviceDetail {
	if x != nil {
		return x.DeviceDetails
	}
	return nil
}

func (x *AnonymizedSiteDetails) GetCity() *wrapperspb.StringValue {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *AnonymizedSiteDetails) GetZip() *wrapperspb.StringValue {
	if x != nil {
		return x.Zip
	}
	return nil
}

type AssetSiteUuidOfDeviceResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AssetSiteUuid *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=assetSiteUuid,proto3" json:"assetSiteUuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetSiteUuidOfDeviceResponse) Reset() {
	*x = AssetSiteUuidOfDeviceResponse{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSiteUuidOfDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSiteUuidOfDeviceResponse) ProtoMessage() {}

func (x *AssetSiteUuidOfDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSiteUuidOfDeviceResponse.ProtoReflect.Descriptor instead.
func (*AssetSiteUuidOfDeviceResponse) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{1}
}

func (x *AssetSiteUuidOfDeviceResponse) GetAssetSiteUuid() *wrapperspb.StringValue {
	if x != nil {
		return x.AssetSiteUuid
	}
	return nil
}

type CustomerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SsoId         *common.UUIDv4         `protobuf:"bytes,1,opt,name=ssoId,proto3" json:"ssoId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	GivenName     string                 `protobuf:"bytes,3,opt,name=givenName,proto3" json:"givenName,omitempty"`
	FamilyName    string                 `protobuf:"bytes,4,opt,name=familyName,proto3" json:"familyName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerInfo) GetSsoId() *common.UUIDv4 {
	if x != nil {
		return x.SsoId
	}
	return nil
}

func (x *CustomerInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CustomerInfo) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *CustomerInfo) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

type CustomerLegalConsent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrivacyNotice   *wrapperspb.BoolValue  `protobuf:"bytes,1,opt,name=privacyNotice,proto3" json:"privacyNotice,omitempty"`
	LimitedWarranty *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=limitedWarranty,proto3" json:"limitedWarranty,omitempty"`
	GridServices    *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=gridServices,proto3" json:"gridServices,omitempty"`
	Marketing       *wrapperspb.BoolValue  `protobuf:"bytes,4,opt,name=marketing,proto3" json:"marketing,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CustomerLegalConsent) Reset() {
	*x = CustomerLegalConsent{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerLegalConsent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLegalConsent) ProtoMessage() {}

func (x *CustomerLegalConsent) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLegalConsent.ProtoReflect.Descriptor instead.
func (*CustomerLegalConsent) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerLegalConsent) GetPrivacyNotice() *wrapperspb.BoolValue {
	if x != nil {
		return x.PrivacyNotice
	}
	return nil
}

func (x *CustomerLegalConsent) GetLimitedWarranty() *wrapperspb.BoolValue {
	if x != nil {
		return x.LimitedWarranty
	}
	return nil
}

func (x *CustomerLegalConsent) GetGridServices() *wrapperspb.BoolValue {
	if x != nil {
		return x.GridServices
	}
	return nil
}

func (x *CustomerLegalConsent) GetMarketing() *wrapperspb.BoolValue {
	if x != nil {
		return x.Marketing
	}
	return nil
}

type CustomerSiteAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerSiteAddress) Reset() {
	*x = CustomerSiteAddress{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSiteAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSiteAddress) ProtoMessage() {}

func (x *CustomerSiteAddress) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSiteAddress.ProtoReflect.Descriptor instead.
func (*CustomerSiteAddress) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerSiteAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CustomerSiteAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CustomerSiteAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CustomerSiteAddress) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *CustomerSiteAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CustomerSiteAddress) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type DeviceDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeviceType          int32                  `protobuf:"varint,1,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	FallbackDescription string                 `protobuf:"bytes,2,opt,name=fallbackDescription,proto3" json:"fallbackDescription,omitempty"`
	Din                 string                 `protobuf:"bytes,3,opt,name=din,proto3" json:"din,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeviceDetail) Reset() {
	*x = DeviceDetail{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDetail) ProtoMessage() {}

func (x *DeviceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDetail.ProtoReflect.Descriptor instead.
func (*DeviceDetail) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceDetail) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *DeviceDetail) GetFallbackDescription() string {
	if x != nil {
		return x.FallbackDescription
	}
	return ""
}

func (x *DeviceDetail) GetDin() string {
	if x != nil {
		return x.Din
	}
	return ""
}

type FirmwareVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Githash       []byte                 `protobuf:"bytes,2,opt,name=githash,proto3" json:"githash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareVersion) Reset() {
	*x = FirmwareVersion{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareVersion) ProtoMessage() {}

func (x *FirmwareVersion) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareVersion.ProtoReflect.Descriptor instead.
func (*FirmwareVersion) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{6}
}

func (x *FirmwareVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirmwareVersion) GetGithash() []byte {
	if x != nil {
		return x.Githash
	}
	return nil
}

type InstallationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InstallationGuid string                 `protobuf:"bytes,1,opt,name=installationGuid,proto3" json:"installationGuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InstallationInfo) Reset() {
	*x = InstallationInfo{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallationInfo) ProtoMessage() {}

func (x *InstallationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallationInfo.ProtoReflect.Descriptor instead.
func (*InstallationInfo) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{7}
}

func (x *InstallationInfo) GetInstallationGuid() string {
	if x != nil {
		return x.InstallationGuid
	}
	return ""
}

type InstallerInfo struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Email           string                  `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	AccountMasterId *common.UUIDv4          `protobuf:"bytes,2,opt,name=accountMasterId,proto3" json:"accountMasterId,omitempty"`
	CompanyName     *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Phone           *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallerInfo) Reset() {
	*x = InstallerInfo{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerInfo) ProtoMessage() {}

func (x *InstallerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerInfo.ProtoReflect.Descriptor instead.
func (*InstallerInfo) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{8}
}

func (x *InstallerInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InstallerInfo) GetAccountMasterId() *common.UUIDv4 {
	if x != nil {
		return x.AccountMasterId
	}
	return nil
}

func (x *InstallerInfo) GetCompanyName() *wrapperspb.StringValue {
	if x != nil {
		return x.CompanyName
	}
	return nil
}

func (x *InstallerInfo) GetPhone() *wrapperspb.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

type InstallerLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallerLocation) Reset() {
	*x = InstallerLocation{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallerLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerLocation) ProtoMessage() {}

func (x *InstallerLocation) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerLocation.ProtoReflect.Descriptor instead.
func (*InstallerLocation) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{9}
}

func (x *InstallerLocation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *InstallerLocation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PartDetail struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PartNumber    string                  `protobuf:"bytes,1,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	SerialNumber  string                  `protobuf:"bytes,2,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	PartType      string                  `protobuf:"bytes,3,opt,name=partType,proto3" json:"partType,omitempty"`
	Manufacturer  *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartDetail) Reset() {
	*x = PartDetail{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartDetail) ProtoMessage() {}

func (x *PartDetail) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartDetail.ProtoReflect.Descriptor instead.
func (*PartDetail) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{10}
}

func (x *PartDetail) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *PartDetail) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *PartDetail) GetPartType() string {
	if x != nil {
		return x.PartType
	}
	return ""
}

func (x *PartDetail) GetManufacturer() *wrapperspb.StringValue {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

type PartnerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountMasterId *common.UUIDv4         `protobuf:"bytes,1,opt,name=accountMasterId,proto3" json:"accountMasterId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartnerInfo) Reset() {
	*x = PartnerInfo{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartnerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerInfo) ProtoMessage() {}

func (x *PartnerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerInfo.ProtoReflect.Descriptor instead.
func (*PartnerInfo) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{11}
}

func (x *PartnerInfo) GetAccountMasterId() *common.UUIDv4 {
	if x != nil {
		return x.AccountMasterId
	}
	return nil
}

type RegistrationRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Version            *FirmwareVersion        `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PartDetails        []*PartDetail           `protobuf:"bytes,2,rep,name=partDetails,proto3" json:"partDetails,omitempty"`
	Attempt            uint32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	RegistrationSource int32                   `protobuf:"varint,4,opt,name=registrationSource,proto3" json:"registrationSource,omitempty"`
	Installer          *InstallerInfo          `protobuf:"bytes,5,opt,name=installer,proto3" json:"installer,omitempty"`
	Customer           *CustomerInfo           `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	SiteAddress        *CustomerSiteAddress    `protobuf:"bytes,7,opt,name=siteAddress,proto3" json:"siteAddress,omitempty"`
	LegalConsent       *CustomerLegalConsent   `protobuf:"bytes,8,opt,name=legalConsent,proto3" json:"legalConsent,omitempty"`
	InstallationInfo   *InstallationInfo       `protobuf:"bytes,9,opt,name=installationInfo,proto3" json:"installationInfo,omitempty"`
	AssetSiteId        *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=assetSiteId,proto3" json:"assetSiteId,omitempty"`
	AdditionalPartners []*PartnerInfo          `protobuf:"bytes,11,rep,name=additionalPartners,proto3" json:"additionalPartners,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{12}
}

func (x *RegistrationRequest) GetVersion() *FirmwareVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RegistrationRequest) GetPartDetails() []*PartDetail {
	if x != nil {
		return x.PartDetails
	}
	return nil
}

func (x *RegistrationRequest) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RegistrationRequest) GetRegistrationSource() int32 {
	if x != nil {
		return x.RegistrationSource
	}
	return 0
}

func (x *RegistrationRequest) GetInstaller() *InstallerInfo {
	if x != nil {
		return x.Installer
	}
	return nil
}

func (x *RegistrationRequest) GetCustomer() *CustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *RegistrationRequest) GetSiteAddress() *CustomerSiteAddress {
	if x != nil {
		return x.SiteAddress
	}
	return nil
}

func (x *RegistrationRequest) GetLegalConsent() *CustomerLegalConsent {
	if x != nil {
		return x.LegalConsent
	}
	return nil
}

func (x *RegistrationRequest) GetInstallationInfo() *InstallationInfo {
	if x != nil {
		return x.InstallationInfo
	}
	return nil
}

func (x *RegistrationRequest) GetAssetSiteId() *wrapperspb.StringValue {
	if x != nil {
		return x.AssetSiteId
	}
	return nil
}

func (x *RegistrationRequest) GetAdditionalPartners() []*PartnerInfo {
	if x != nil {
		return x.AdditionalPartners
	}
	return nil
}

type RegistrationResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        int32                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RetryDelayS   uint32                  `protobuf:"varint,2,opt,name=retryDelayS,proto3" json:"retryDelayS,omitempty"`
	StatusTime    *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=statusTime,proto3" json:"statusTime,omitempty"`
	AssetSiteId   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=assetSiteId,proto3" json:"assetSiteId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{13}
}

func (x *RegistrationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RegistrationResponse) GetRetryDelayS() uint32 {
	if x != nil {
		return x.RetryDelayS
	}
	return 0
}

func (x *RegistrationResponse) GetStatusTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusTime
	}
	return nil
}

func (x *RegistrationResponse) GetAssetSiteId() *wrapperspb.StringValue {
	if x != nil {
		return x.AssetSiteId
	}
	return nil
}

type SiteSuggestion struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AssetSiteUuid         string                 `protobuf:"bytes,1,opt,name=assetSiteUuid,proto3" json:"assetSiteUuid,omitempty"`
	AnonymizedSiteDetails *AnonymizedSiteDetails `protobuf:"bytes,2,opt,name=anonymizedSiteDetails,proto3" json:"anonymizedSiteDetails,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SiteSuggestion) Reset() {
	*x = SiteSuggestion{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSuggestion) ProtoMessage() {}

func (x *SiteSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSuggestion.ProtoReflect.Descriptor instead.
func (*SiteSuggestion) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{14}
}

func (x *SiteSuggestion) GetAssetSiteUuid() string {
	if x != nil {
		return x.AssetSiteUuid
	}
	return ""
}

func (x *SiteSuggestion) GetAnonymizedSiteDetails() *AnonymizedSiteDetails {
	if x != nil {
		return x.AnonymizedSiteDetails
	}
	return nil
}

type SiteSuggestionRequest struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Lookup                        string                 `protobuf:"bytes,1,opt,name=lookup,proto3" json:"lookup,omitempty"`
	InstallerLocation             *InstallerLocation     `protobuf:"bytes,2,opt,name=installerLocation,proto3" json:"installerLocation,omitempty"`
	InstallerTeslaAuthBearerToken string                 `protobuf:"bytes,3,opt,name=installerTeslaAuthBearerToken,proto3" json:"installerTeslaAuthBearerToken,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SiteSuggestionRequest) Reset() {
	*x = SiteSuggestionRequest{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSuggestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSuggestionRequest) ProtoMessage() {}

func (x *SiteSuggestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSuggestionRequest.ProtoReflect.Descriptor instead.
func (*SiteSuggestionRequest) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{15}
}

func (x *SiteSuggestionRequest) GetLookup() string {
	if x != nil {
		return x.Lookup
	}
	return ""
}

func (x *SiteSuggestionRequest) GetInstallerLocation() *InstallerLocation {
	if x != nil {
		return x.InstallerLocation
	}
	return nil
}

func (x *SiteSuggestionRequest) GetInstallerTeslaAuthBearerToken() string {
	if x != nil {
		return x.InstallerTeslaAuthBearerToken
	}
	return ""
}

type SiteSuggestionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SiteSuggestions []*SiteSuggestion      `protobuf:"bytes,1,rep,name=siteSuggestions,proto3" json:"siteSuggestions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SiteSuggestionResponse) Reset() {
	*x = SiteSuggestionResponse{}
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteSuggestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteSuggestionResponse) ProtoMessage() {}

func (x *SiteSuggestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tedapi_v2_energy_registration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteSuggestionResponse.ProtoReflect.Descriptor instead.
func (*SiteSuggestionResponse) Descriptor() ([]byte, []int) {
	return file_tedapi_v2_energy_registration_proto_rawDescGZIP(), []int{16}
}

func (x *SiteSuggestionResponse) GetSiteSuggestions() []*SiteSuggestion {
	if x != nil {
		return x.SiteSuggestions
	}
	return nil
}

var File_tedapi_v2_energy_registration_proto protoreflect.FileDescriptor

const file_tedapi_v2_energy_registration_proto_rawDesc = "" +
	"\n" +
	"#tedapi_v2_energy_registration.proto\x12\"tesla.proto.energy_registration.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x16tedapi_v2_common.proto\"\xd1\x01\n" +
	"\x15AnonymizedSiteDetails\x12V\n" +
	"\rdeviceDetails\x18\x01 \x03(\v20.tesla.proto.energy_registration.v1.DeviceDetailR\rdeviceDetails\x120\n" +
	"\x04city\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04city\x12.\n" +
	"\x03zip\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x03zip\"c\n" +
	"\x1dAssetSiteUuidOfDeviceResponse\x12B\n" +
	"\rassetSiteUuid\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\rassetSiteUuid\"\x97\x01\n" +
	"\fCustomerInfo\x123\n" +
	"\x05ssoId\x18\x01 \x01(\v2\x1d.tesla.proto.common.v1.UUIDv4R\x05ssoId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tgivenName\x18\x03 \x01(\tR\tgivenName\x12\x1e\n" +
	"\n" +
	"familyName\x18\x04 \x01(\tR\n" +
	"familyName\"\x98\x02\n" +
	"\x14CustomerLegalConsent\x12@\n" +
	"\rprivacyNotice\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\rprivacyNotice\x12D\n" +
	"\x0flimitedWarranty\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x0flimitedWarranty\x12>\n" +
	"\fgridServices\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\fgridServices\x128\n" +
	"\tmarketing\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\tmarketing\"\x99\x01\n" +
	"\x13CustomerSiteAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x04 \x01(\tR\x03zip\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\"r\n" +
	"\fDeviceDetail\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x01 \x01(\x05R\n" +
	"deviceType\x120\n" +
	"\x13fallbackDescription\x18\x02 \x01(\tR\x13fallbackDescription\x12\x10\n" +
	"\x03din\x18\x03 \x01(\tR\x03din\"E\n" +
	"\x0fFirmwareVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\agithash\x18\x02 \x01(\fR\agithash\">\n" +
	"\x10InstallationInfo\x12*\n" +
	"\x10installationGuid\x18\x01 \x01(\tR\x10installationGuid\"\xe2\x01\n" +
	"\rInstallerInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12G\n" +
	"\x0faccountMasterId\x18\x02 \x01(\v2\x1d.tesla.proto.common.v1.UUIDv4R\x0faccountMasterId\x12>\n" +
	"\vcompanyName\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vcompanyName\x122\n" +
	"\x05phone\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\"M\n" +
	"\x11InstallerLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\"\xae\x01\n" +
	"\n" +
	"PartDetail\x12\x1e\n" +
	"\n" +
	"partNumber\x18\x01 \x01(\tR\n" +
	"partNumber\x12\"\n" +
	"\fserialNumber\x18\x02 \x01(\tR\fserialNumber\x12\x1a\n" +
	"\bpartType\x18\x03 \x01(\tR\bpartType\x12@\n" +
	"\fmanufacturer\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\fmanufacturer\"V\n" +
	"\vPartnerInfo\x12G\n" +
	"\x0faccountMasterId\x18\x01 \x01(\v2\x1d.tesla.proto.common.v1.UUIDv4R\x0faccountMasterId\"\xdb\x06\n" +
	"\x13RegistrationRequest\x12M\n" +
	"\aversion\x18\x01 \x01(\v23.tesla.proto.energy_registration.v1.FirmwareVersionR\aversion\x12P\n" +
	"\vpartDetails\x18\x02 \x03(\v2..tesla.proto.energy_registration.v1.PartDetailR\vpartDetails\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12.\n" +
	"\x12registrationSource\x18\x04 \x01(\x05R\x12registrationSource\x12O\n" +
	"\tinstaller\x18\x05 \x01(\v21.tesla.proto.energy_registration.v1.InstallerInfoR\tinstaller\x12L\n" +
	"\bcustomer\x18\x06 \x01(\v20.tesla.proto.energy_registration.v1.CustomerInfoR\bcustomer\x12Y\n" +
	"\vsiteAddress\x18\a \x01(\v27.tesla.proto.energy_registration.v1.CustomerSiteAddressR\vsiteAddress\x12\\\n" +
	"\flegalConsent\x18\b \x01(\v28.tesla.proto.energy_registration.v1.CustomerLegalConsentR\flegalConsent\x12`\n" +
	"\x10installationInfo\x18\t \x01(\v24.tesla.proto.energy_registration.v1.InstallationInfoR\x10installationInfo\x12>\n" +
	"\vassetSiteId\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\vassetSiteId\x12_\n" +
	"\x12additionalPartners\x18\v \x03(\v2/.tesla.proto.energy_registration.v1.PartnerInfoR\x12additionalPartners\"\xcc\x01\n" +
	"\x14RegistrationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12 \n" +
	"\vretryDelayS\x18\x02 \x01(\rR\vretryDelayS\x12:\n" +
	"\n" +
	"statusTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"statusTime\x12>\n" +
	"\vassetSiteId\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vassetSiteId\"\xa7\x01\n" +
	"\x0eSiteSuggestion\x12$\n" +
	"\rassetSiteUuid\x18\x01 \x01(\tR\rassetSiteUuid\x12o\n" +
	"\x15anonymizedSiteDetails\x18\x02 \x01(\v29.tesla.proto.energy_registration.v1.AnonymizedSiteDetailsR\x15anonymizedSiteDetails\"\xda\x01\n" +
	"\x15SiteSuggestionRequest\x12\x16\n" +
	"\x06lookup\x18\x01 \x01(\tR\x06lookup\x12c\n" +
	"\x11installerLocation\x18\x02 \x01(\v25.tesla.proto.energy_registration.v1.InstallerLocationR\x11installerLocation\x12D\n" +
	"\x1dinstallerTeslaAuthBearerToken\x18\x03 \x01(\tR\x1dinstallerTeslaAuthBearerToken\"v\n" +
	"\x16SiteSuggestionResponse\x12\\\n" +
	"\x0fsiteSuggestions\x18\x01 \x03(\v22.tesla.proto.energy_registration.v1.SiteSuggestionR\x0fsiteSuggestions*\xe2\x01\n" +
	"\x11ProjectAccessType\x12\x1f\n" +
	"\x1bPROJECT_ACCESS_TYPE_INVALID\x10\x00\x12\x1f\n" +
	"\x1bPROJECT_ACCESS_TYPE_SERVICE\x10\x01\x12%\n" +
	"!PROJECT_ACCESS_TYPE_MANUFACTURING\x10\x02\x12#\n" +
	"\x1fPROJECT_ACCESS_TYPE_ENGINEERING\x10\x03\x12\x1f\n" +
	"\x1bPROJECT_ACCESS_TYPE_PRIVATE\x10\x04\x12\x1e\n" +
	"\x1aPROJECT_ACCESS_TYPE_PUBLIC\x10\x05*\x9e\x06\n" +
	"\fPropertyType\x12\x19\n" +
	"\x15PROPERTY_TYPE_INVALID\x10\x00\x12&\n" +
	"\"PROPERTY_TYPE_SHOPPING_MALL_CENTER\x10\x01\x12\x1c\n" +
	"\x18PROPERTY_TYPE_RESTAURANT\x10\x02\x12\x1d\n" +
	"\x19PROPERTY_TYPE_GAS_STATION\x10\x03\x12)\n" +
	"%PROPERTY_TYPE_SERVICE_PLAZA_REST_AREA\x10\x04\x12.\n" +
	"*PROPERTY_TYPE_HOTEL_RESORT_TOURIST_COMPLEX\x10\x05\x12\x1f\n" +
	"\x1bPROPERTY_TYPE_GROCERY_STORE\x10\x06\x12,\n" +
	"(PROPERTY_TYPE_TESLA_STORE_SERVICE_CENTER\x10\a\x12\x18\n" +
	"\x14PROPERTY_TYPE_OFFICE\x10\b\x12&\n" +
	"\"PROPERTY_TYPE_RESIDENTIAL_BUILDING\x10\t\x123\n" +
	"/PROPERTY_TYPE_PARKING_GARAGE_PUBLIC_PARKING_LOT\x10\n" +
	"\x12\x16\n" +
	"\x12PROPERTY_TYPE_BANK\x10\v\x12\x19\n" +
	"\x15PROPERTY_TYPE_AIRPORT\x10\f\x123\n" +
	"/PROPERTY_TYPE_CITY_VISITOR_CENTER_CITY_PROPERTY\x10\r\x12-\n" +
	")PROPERTY_TYPE_MUSEUM_AMUSEMENT_ATTRACTION\x10\x0e\x12#\n" +
	"\x1fPROPERTY_TYPE_UNIVERSITY_SCHOOL\x10\x0f\x12\x18\n" +
	"\x14PROPERTY_TYPE_WINERY\x10\x10\x12\x1c\n" +
	"\x18PROPERTY_TYPE_AUTOMOTIVE\x10\x11\x12\x1b\n" +
	"\x17PROPERTY_TYPE_MIXED_USE\x10\x12\x12\x1c\n" +
	"\x18PROPERTY_TYPE_RECREATION\x10\x13\x12!\n" +
	"\x1dPROPERTY_TYPE_RENTAL_PROPERTY\x10\x14\x12\x1b\n" +
	"\x17PROPERTY_TYPE_WORKPLACE\x10\x15*\xcd\x02\n" +
	"\x16RegistrationDeviceType\x12$\n" +
	" REGISTRATION_DEVICE_TYPE_INVALID\x10\x00\x12&\n" +
	"\"REGISTRATION_DEVICE_TYPE_POWERWALL\x10\x01\x120\n" +
	",REGISTRATION_DEVICE_TYPE_POWERWALL_EXPANSION\x10\x02\x12(\n" +
	"$REGISTRATION_DEVICE_TYPE_PV_INVERTER\x10\x03\x12+\n" +
	"'REGISTRATION_DEVICE_TYPE_WALL_CONNECTOR\x10\x04\x12(\n" +
	"$REGISTRATION_DEVICE_TYPE_POWERWALL_3\x10\x05\x122\n" +
	".REGISTRATION_DEVICE_TYPE_POWERWALL_3_EXPANSION\x10\x06*{\n" +
	"\x13RegistrationFailure\x12 \n" +
	"\x1cREGISTRATION_FAILURE_INVALID\x10\x00\x12 \n" +
	"\x1cREGISTRATION_FAILURE_DEVICES\x10\x01\x12 \n" +
	"\x1cREGISTRATION_FAILURE_NETWORK\x10\x02*\x9e\x01\n" +
	"\x12RegistrationSource\x12\x1f\n" +
	"\x1bREGISTRATION_SOURCE_INVALID\x10\x00\x12\"\n" +
	"\x1eREGISTRATION_SOURCE_AUTOCONFIG\x10\x01\x12!\n" +
	"\x1dREGISTRATION_SOURCE_INSTALLER\x10\x02\x12 \n" +
	"\x1cREGISTRATION_SOURCE_CUSTOMER\x10\x03*\xff\x01\n" +
	"\x12RegistrationStatus\x12\x1f\n" +
	"\x1bREGISTRATION_STATUS_INVALID\x10\x00\x12$\n" +
	" REGISTRATION_STATUS_MISSING_INFO\x10\x01\x12 \n" +
	"\x1cREGISTRATION_STATUS_UNDERWAY\x10\x02\x12*\n" +
	"&REGISTRATION_STATUS_ALREADY_REGISTERED\x10\x03\x12\x1e\n" +
	"\x1aREGISTRATION_STATUS_FAILED\x10\x04\x124\n" +
	"0REGISTRATION_STATUS_RETRY_WITH_NO_FURTHER_ACTION\x10\x05*\x8f\x01\n" +
	"\x16SiteRegistrationStatus\x12$\n" +
	" SITE_REGISTRATION_STATUS_INVALID\x10\x00\x12'\n" +
	"#SITE_REGISTRATION_STATUS_REGISTERED\x10\x01\x12&\n" +
	"\"SITE_REGISTRATION_STATUS_ABANDONED\x10\x02*y\n" +
	"\x11WCLoadSharingType\x12 \n" +
	"\x1cWC_LOAD_SHARING_TYPE_INVALID\x10\x00\x12\x1f\n" +
	"\x1bWC_LOAD_SHARING_TYPE_LEADER\x10\x01\x12!\n" +
	"\x1dWC_LOAD_SHARING_TYPE_FOLLOWER\x10\x02BPZNgithub.com/blackbirdworks/gopowerwall/proto/tedapiv2/registration;registrationb\x06proto3"

var (
	file_tedapi_v2_energy_registration_proto_rawDescOnce sync.Once
	file_tedapi_v2_energy_registration_proto_rawDescData []byte
)

func file_tedapi_v2_energy_registration_proto_rawDescGZIP() []byte {
	file_tedapi_v2_energy_registration_proto_rawDescOnce.Do(func() {
		file_tedapi_v2_energy_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tedapi_v2_energy_registration_proto_rawDesc), len(file_tedapi_v2_energy_registration_proto_rawDesc)))
	})
	return file_tedapi_v2_energy_registration_proto_rawDescData
}

var file_tedapi_v2_energy_registration_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_tedapi_v2_energy_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_tedapi_v2_energy_registration_proto_goTypes = []any{
	(ProjectAccessType)(0),                // 0: tesla.proto.energy_registration.v1.ProjectAccessType
	(PropertyType)(0),                     // 1: tesla.proto.energy_registration.v1.PropertyType
	(RegistrationDeviceType)(0),           // 2: tesla.proto.energy_registration.v1.RegistrationDeviceType
	(RegistrationFailure)(0),              // 3: tesla.proto.energy_registration.v1.RegistrationFailure
	(RegistrationSource)(0),               // 4: tesla.proto.energy_registration.v1.RegistrationSource
	(RegistrationStatus)(0),               // 5: tesla.proto.energy_registration.v1.RegistrationStatus
	(SiteRegistrationStatus)(0),           // 6: tesla.proto.energy_registration.v1.SiteRegistrationStatus
	(WCLoadSharingType)(0),                // 7: tesla.proto.energy_registration.v1.WCLoadSharingType
	(*AnonymizedSiteDetails)(nil),         // 8: tesla.proto.energy_registration.v1.AnonymizedSiteDetails
	(*AssetSiteUuidOfDeviceResponse)(nil), // 9: tesla.proto.energy_registration.v1.AssetSiteUuidOfDeviceResponse
	(*CustomerInfo)(nil),                  // 10: tesla.proto.energy_registration.v1.CustomerInfo
	(*CustomerLegalConsent)(nil),          // 11: tesla.proto.energy_registration.v1.CustomerLegalConsent
	(*CustomerSiteAddress)(nil),           // 12: tesla.proto.energy_registration.v1.CustomerSiteAddress
	(*DeviceDetail)(nil),                  // 13: tesla.proto.energy_registration.v1.DeviceDetail
	(*FirmwareVersion)(nil),               // 14: tesla.proto.energy_registration.v1.FirmwareVersion
	(*InstallationInfo)(nil),              // 15: tesla.proto.energy_registration.v1.InstallationInfo
	(*InstallerInfo)(nil),                 // 16: tesla.proto.energy_registration.v1.InstallerInfo
	(*InstallerLocation)(nil),             // 17: tesla.proto.energy_registration.v1.InstallerLocation
	(*PartDetail)(nil),                    // 18: tesla.proto.energy_registration.v1.PartDetail
	(*PartnerInfo)(nil),                   // 19: tesla.proto.energy_registration.v1.PartnerInfo
	(*RegistrationRequest)(nil),           // 20: tesla.proto.energy_registration.v1.RegistrationRequest
	(*RegistrationResponse)(nil),          // 21: tesla.proto.energy_registration.v1.RegistrationResponse
	(*SiteSuggestion)(nil),                // 22: tesla.proto.energy_registration.v1.SiteSuggestion
	(*SiteSuggestionRequest)(nil),         // 23: tesla.proto.energy_registration.v1.SiteSuggestionRequest
	(*SiteSuggestionResponse)(nil),        // 24: tesla.proto.energy_registration.v1.SiteSuggestionResponse
	(*wrapperspb.StringValue)(nil),        // 25: google.protobuf.StringValue
	(*common.UUIDv4)(nil),                 // 26: tesla.proto.common.v1.UUIDv4
	(*wrapperspb.BoolValue)(nil),          // 27: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),         // 28: google.protobuf.Timestamp
}
var file_tedapi_v2_energy_registration_proto_depIdxs = []int32{
	13, // 0: tesla.proto.energy_registration.v1.AnonymizedSiteDetails.deviceDetails:type_name -> tesla.proto.energy_registration.v1.DeviceDetail
	25, // 1: tesla.proto.energy_registration.v1.AnonymizedSiteDetails.city:type_name -> google.protobuf.StringValue
	25, // 2: tesla.proto.energy_registration.v1.AnonymizedSiteDetails.zip:type_name -> google.protobuf.StringValue
	25, // 3: tesla.proto.energy_registration.v1.AssetSiteUuidOfDeviceResponse.assetSiteUuid:type_name -> google.protobuf.StringValue
	26, // 4: tesla.proto.energy_registration.v1.CustomerInfo.ssoId:type_name -> tesla.proto.common.v1.UUIDv4
	27, // 5: tesla.proto.energy_registration.v1.CustomerLegalConsent.privacyNotice:type_name -> google.protobuf.BoolValue
	27, // 6: tesla.proto.energy_registration.v1.CustomerLegalConsent.limitedWarranty:type_name -> google.protobuf.BoolValue
	27, // 7: tesla.proto.energy_registration.v1.CustomerLegalConsent.gridServices:type_name -> google.protobuf.BoolValue
	27, // 8: tesla.proto.energy_registration.v1.CustomerLegalConsent.marketing:type_name -> google.protobuf.BoolValue
	26, // 9: tesla.proto.energy_registration.v1.InstallerInfo.accountMasterId:type_name -> tesla.proto.common.v1.UUIDv4
	25, // 10: tesla.proto.energy_registration.v1.InstallerInfo.companyName:type_name -> google.protobuf.StringValue
	25, // 11: tesla.proto.energy_registration.v1.InstallerInfo.phone:type_name -> google.protobuf.StringValue
	25, // 12: tesla.proto.energy_registration.v1.PartDetail.manufacturer:type_name -> google.protobuf.StringValue
	26, // 13: tesla.proto.energy_registration.v1.PartnerInfo.accountMasterId:type_name -> tesla.proto.common.v1.UUIDv4
	14, // 14: tesla.proto.energy_registration.v1.RegistrationRequest.version:type_name -> tesla.proto.energy_registration.v1.FirmwareVersion
	18, // 15: tesla.proto.energy_registration.v1.RegistrationRequest.partDetails:type_name -> tesla.proto.energy_registration.v1.PartDetail
	16, // 16: tesla.proto.energy_registration.v1.RegistrationRequest.installer:type_name -> tesla.proto.energy_registration.v1.InstallerInfo
	10, // 17: tesla.proto.energy_registration.v1.RegistrationRequest.customer:type_name -> tesla.proto.energy_registration.v1.CustomerInfo
	12, // 18: tesla.proto.energy_registration.v1.RegistrationRequest.siteAddress:type_name -> tesla.proto.energy_registration.v1.CustomerSiteAddress
	11, // 19: tesla.proto.energy_registration.v1.RegistrationRequest.legalConsent:type_name -> tesla.proto.energy_registration.v1.CustomerLegalConsent
	15, // 20: tesla.proto.energy_registration.v1.RegistrationRequest.installationInfo:type_name -> tesla.proto.energy_registration.v1.InstallationInfo
	25, // 21: tesla.proto.energy_registration.v1.RegistrationRequest.assetSiteId:type_name -> google.protobuf.StringValue
	19, // 22: tesla.proto.energy_registration.v1.RegistrationRequest.additionalPartners:type_name -> tesla.proto.energy_registration.v1.PartnerInfo
	28, // 23: tesla.proto.energy_registration.v1.RegistrationResponse.statusTime:type_name -> google.protobuf.Timestamp
	25, // 24: tesla.proto.energy_registration.v1.RegistrationResponse.assetSiteId:type_name -> google.protobuf.StringValue
	8,  // 25: tesla.proto.energy_registration.v1.SiteSuggestion.anonymizedSiteDetails:type_name -> tesla.proto.energy_registration.v1.AnonymizedSiteDetails
	17, // 26: tesla.proto.energy_registration.v1.SiteSuggestionRequest.installerLocation:type_name -> tesla.proto.energy_registration.v1.InstallerLocation
	22, // 27: tesla.proto.energy_registration.v1.SiteSuggestionResponse.siteSuggestions:type_name -> tesla.proto.energy_registration.v1.SiteSuggestion
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_tedapi_v2_energy_registration_proto_init() }
func file_tedapi_v2_energy_registration_proto_init() {
	if File_tedapi_v2_energy_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tedapi_v2_energy_registration_proto_rawDesc), len(file_tedapi_v2_energy_registration_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tedapi_v2_energy_registration_proto_goTypes,
		DependencyIndexes: file_tedapi_v2_energy_registration_proto_depIdxs,
		EnumInfos:         file_tedapi_v2_energy_registration_proto_enumTypes,
		MessageInfos:      file_tedapi_v2_energy_registration_proto_msgTypes,
	}.Build()
	File_tedapi_v2_energy_registration_proto = out.File
	file_tedapi_v2_energy_registration_proto_goTypes = nil
	file_tedapi_v2_energy_registration_proto_depIdxs = nil
}
